function getComputerChoice(){
    // Return paper, rock, or scissor based on the random integer that is generated by the computer
    let random=Math.random();
    let rand_int=random*3;
    rand_int=Math.floor(rand_int)
    switch (rand_int){
        case 0:
            return ("rock");
            break;
        case 1:
            return("paper");
            break;
        case 2:
             return ("scissor")
            break;
    }
}

function one_Round(playerSelection, computerSelection){
    playerSelection = playerSelection.toLowerCase();
    if (playerSelection == computerSelection){
        return "Its a tie";
    } else if (playerSelection == "rock" && computerSelection=="scissors"){;
        return "You Win :)"
    } else if (playerSelection == "scissors" && computerSelection=="paper"){;
        return "You Win :)"
    } else if(playerSelection == "paper" && computerSelection=="rock"){;
        return "You Win :)"
    } else{
        return "You Lost :("
    }
}

function game(){
    let playerScore=0;
    let computerScore=0;
    let count=0;
    while(count<10){;
    let playerSelection = prompt("Enter your choice");
    let computerSelection=getComputerChoice();
    if (playerScore == 5|| computerScore==5){
        break;
    }else{
        let result=one_Round(playerSelection,computerSelection)
        console.log(result);
        if (result =="You Win :)"){
            playerScore++;
            count +=1;
        }else if (result == "You Lost :("){
            computerScore++;
            count+=1;
        } else{
            continue;
        }
      }
    }
    if (playerScore ==5){
        return "Congrats You Win";
    }else{
        return "Game Over You Lost";
    }
}